spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 100

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DB:0}
      timeout: ${REDIS_TIMEOUT_MS:2000ms}
      ssl:
        enabled: ${REDIS_SSL:false}

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-ms: ${JWT_ACCESS_TOKEN_EXPIRE_MS}
  refresh-token-expire-ms: ${JWT_REFRESH_TOKEN_EXPIRE_MS}
  header: ${JWT_HEADER}